<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
use Phalcon\Tag; ?>

<div class="page-header">
    <h2>
        Все автомобили
    </h2>
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["orders/new", "Добавить автомобиль "]); ?></li>           
        </ul>
    </nav>
</div>


<?php echo $this->getContent() ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id автомобиля</th>
            <th>Id пользователя</th>
            <th>Автомобиль</th>
            <th>Цена</th>
            <th>Фотография</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $order): ?>
            <tr>
                <td><?php echo $order->_id ?></td>
            <td><?php echo $order->id_user ?></td>
            <td><?php echo $order->avto ?></td>
            <td><?php echo $order->price ?></td>
            <td><div class="image"><?php echo $this->tag->image("img/$order->img"); ?></div></td>


                <td><?php echo $this->tag->linkTo(["orders/edit/" . $order->_id, "Редактировать"]); ?></td>
                <td><?php echo $this->tag->linkTo(["orders/delete/" . $order->_id, "Удалить"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("orders", "Первая") ?></li>
                <li><?php echo $this->tag->linkTo("orders?page=" . $page->before, "Предыдущая") ?></li>
                <li><?php echo $this->tag->linkTo("orders?page=" . $page->next, "Следующая") ?></li>
                <li><?php echo $this->tag->linkTo("orders?page=" . $page->last, "Последняя") ?></li>
            </ul>
        </nav>
    </div>
</div> 

<div class="page-header">
    <h1>
        Поиск автомобиля
    </h1>
</div>

<?php
    echo $this->tag->form(
        [
            "orders/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>


<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["_id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdUser" class="col-sm-2 control-label">Id Of User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_user", "type" => "number", "class" => "form-control", "id" => "fieldIdUser"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAvto" class="col-sm-2 control-label">Avto</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["avto", "size" => 30, "class" => "form-control", "id" => "fieldAvto"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImg" class="col-sm-2 control-label">Img</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["img", "size" => 30, "class" => "form-control", "id" => "fieldImg"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>



<?php echo $this->tag->endForm(); ?>
