<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
use Phalcon\Tag; ?>

<div class="page-header">
    <h3>
        Новые не подтвержденные пользователи
    </h3>

</div>


<?php echo $this->getContent() ?>

<div class="row">
    <table class="table table-bordered table_user">
        <thead>
            <tr>
                <th>Id пользователя</th>
                <th>E-mail пользователя</th>            
                <th>Роль</th>
                <th>Active</th>
                <th>Uid</th>
                <th>Соц сеть</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->_id ?></td>
            <td><?php echo $user->email ?></td>            
            <td><?php echo $user->role_id ?></td>
            <td><?php echo $user->active ?></td>

            <td><?php echo $user->uid ?></td>
            <td><?php echo $user->social ?></td>
            <td><?php echo $user->first_name ?></td>
            <td><?php echo $user->last_name ?></td>

                <td><?php echo $this->tag->linkTo(["user/confirm/" . $user->_id, "Подтвердить"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user/delete/" . $user->_id, "Удалить"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("user", "Первая") ?></li>
                <li><?php echo $this->tag->linkTo("user?page=" . $page->before, "Предыдущая") ?></li>
                <li><?php echo $this->tag->linkTo("user?page=" . $page->next, "Следующая") ?></li>
                <li><?php echo $this->tag->linkTo("user?page=" . $page->last, "Последняя") ?></li>
            </ul>
        </nav>
    </div>
</div>

