<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["user/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Email</th>
            <th>Pass</th>
            <th>Role</th>
            <th>Active</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->_id ?></td>
            <td><?php echo $user->email ?></td>
            <td><?php echo $user->pass ?></td>
            <td><?php echo $user->role_id ?></td>
            <td><?php echo $user->active ?></td>

                <td><?php echo $this->tag->linkTo(["user/edit/" . $user->_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user/delete/" . $user->_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("user/search", "Первая") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->before, "Предыдущая") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->next, "Следующая") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->last, "Последняя") ?></li>
            </ul>
        </nav>
    </div>
</div>
