<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["cars", "Назад"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h3>
        Редактирование автомобиля
    </h3>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "cars/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>


<div class="form-group">
    <label for="field_Id" class="col-sm-2 control-label">Id автомобиля</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["_id", "type" => "number", "class" => "form-control", "id" => "field_Id"]) ?>
    </div>
</div>



<!-- <div class="form-group">
    <label for="fieldIdUser" class="col-sm-2 control-label">Id пользователя</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_user", "type" => "number", "class" => "form-control", "id" => "fieldIdUser"]) ?>
    </div>
</div> -->

<div class="form-group">
    <label for="fieldAvto" class="col-sm-2 control-label">Автомобиль</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["avto", "size" => 30, "class" => "form-control", "id" => "fieldAvto"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Цена</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImg" class="col-sm-2 control-label">Фотография</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["img", "size" => 30, "class" => "form-control", "id" => "fieldImg"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Сохранить", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
