<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
	<nav>
		<ul class="pager">
			<li class="previous"><?php echo $this->tag->linkTo(["cars", "Назад"]) ?></li>
		</ul>
	</nav>
</div>

<div class="page-header">
	<h3>
		Добавление нового автомобиля
	</h3>
</div>

<?php echo $this->getContent(); ?>

<?php
echo $this->tag->form(
	[
	"cars/create",
	"autocomplete" => "off",
	"class" => "form-horizontal"
	]
	);
	?>

<!-- <div class="form-group">
	<label for="fieldIdUser" class="col-sm-2 control-label">Id Of User</label>
	<div class="col-sm-10">
		<?php echo $this->tag->textField(["id_user", "type" => "number", "class" => "form-control", "id" => "fieldIdUser"]) ?>
	</div>
</div> -->

<div class="form-group">
	<label for="fieldAvto" class="col-sm-2 control-label">Avto</label>
	<div class="col-sm-10">
		<?php echo $this->tag->textField(["avto", "size" => 30, "class" => "form-control", "id" => "fieldAvto"]) ?>
	</div>
</div>

<div class="form-group">
	<label for="fieldPrice" class="col-sm-2 control-label">Price</label>
	<div class="col-sm-10">
		<?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
	</div>
</div>

<div class="form-group">        
	<div class="col-sm-10">
		<?php echo $this->tag->hiddenField (["img", "size" => 30, "class" => "form-control", "id" => "img_form"]) ?>
	</div>
</div>

<div class="form-group picture_add">
	<div class=""><label for="img" class="col-sm-2 control-label">Фотография</label>
		<div id="uploadButton" class="btn btn-info ">
			<font>Выбрать файл</font>
			<img id="load" src=''/><?php echo $this->tag->image("img/loadstop.gif"); ?>
		</div>

		<div id="files" type="text" name="img" value="">
			<ol>
				Загруженные файлы :
			</ol>
		</div>
	</div>	
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<?php echo $this->tag->submitButton(["Сохранить", "class" => "btn btn-success"]) ?>
	</div>
</div>

<?php echo $this->tag->endForm(); ?>
