<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
echo $this->tag->stylesheetLink("css/styles.css");
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["orders", "Главная ORDERS"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["orders/new", "Добавить автомобиль"]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Найденные автомобили</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Id Of User</th>
            <th>Avto</th>
            <th>Price</th>
            <th>Img</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $order): ?>
            <tr>
                <td><?php echo $order->_id ?></td>
            <td><?php echo $order->id_user ?></td>
            <td><?php echo $order->avto ?></td>
            <td><?php echo $order->price ?></td>
            <td><?php echo $order->img ?></td>

                <td><?php echo $this->tag->linkTo(["orders/edit/" . $order->_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["orders/delete/" . $order->_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("orders/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("orders/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("orders/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("orders/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
